<?php

namespace App\Repository;

/**
 * ItemPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPartRepository extends \Doctrine\ORM\EntityRepository
{
	// Find all the parts and portions of an item 
	public function findItem($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'SELECT DISTINCT ip.id as id, s.name as name, ip.portion as portions FROM App\Entity\Item i, App\Entity\Stock s, App\Entity\ItemPart ip WHERE s.id = ip.stockId AND i.id = ip.itemId AND i.id = :id AND ip.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// 
	public function findByItem($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'SELECT ip FROM App\Entity\ItemPart ip WHERE ip.itemId = :id AND ip.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	public function deleteByItem($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'DELETE FROM App\Entity\ItemPart ip WHERE ip.itemId = :id AND ip.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// 
	public function findByStock($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'SELECT ip FROM App\Entity\ItemPart ip WHERE ip.stockId = :id AND ip.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	public function deleteByStock($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'DELETE FROM App\Entity\ItemPart ip WHERE ip.stockId = :id AND ip.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}
}
