<?php

namespace App\Repository;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Doctrine\ORM\EntityRepository
{
	// Select all the items in an order
	public function findOrder($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'SELECT i.name as name, oi.price as price, oi.discount as discount, oi.quantity as quantity FROM App\Entity\OrderItem oi, App\Entity\Item i WHERE oi.orderId = :orderId AND oi.itemId = i.id AND oi.userId = :user'
	        )->setParameter('orderId', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// Delete item belonging to an order
	public function deleteOrderItem($orderid, $itemid, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'DELETE FROM App\Entity\OrderItem oi WHERE oi.orderId = :orderId AND oi.itemId = :itemId AND oi.userId = :user'
	        )->setParameter('orderId', $orderid)
	        ->setParameter('itemId', $itemid)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// Delete items from an order
	public function deleteOrderItems($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'DELETE FROM App\Entity\OrderItem oi WHERE oi.orderId = :id AND oi.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// Find order item
	public function findItem($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'SELECT oi FROM App\Entity\OrderItem oi WHERE oi.itemId = :id AND oi.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// Find items by order
	public function findByOrder($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'SELECT oi FROM App\Entity\OrderItem oi WHERE oi.orderId = :id AND oi.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	public function findOrderItems($order_id, $user)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT oi.price, oi.quantity, oi.discount, it.name FROM App\Entity\OrderItem oi, App\Entity\Item it WHERE oi.itemId = it.id AND oi.userId = :user AND it.userId = :user
				AND oi.orderId = :order_id'
			)->setParameter('order_id', $order_id)
	        ->setParameter('user', $user)
	        ->getResult();
	}

	// Delete items in an order
	public function deleteByOrder($id, $user)
	{
	    return $this->getEntityManager()
	        ->createQuery(
	            'DELETE FROM App\Entity\OrderItem oi WHERE oi.orderId = :id AND oi.userId = :user'
	        )->setParameter('id', $id)
	        ->setParameter('user', $user)
	        ->getResult();
	}
}
